services:
  app:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/data:/mosquitto/data:delegated
      - ./mosquitto/log:/mosquitto/log:delegated
      - ./mosquitto/config:/mosquitto/config:delegated